<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih                Fi</name>
   <tag></tag>
   <elementGuidId>99476136-7753-46ac-a197-fd1c923b45d8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>multipage_form_2_childReqBusinessConditions_subDtlBusinesCond_formDetailsBusinessConditions_dtl_business_condition973321</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>multipage_form_2_childReqBusinessConditions_subDtlBusinesCond_formDetailsBusinessConditions_dtl_business_condition</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Pilih
                Fiktif
                Omzet Menurun
                Test
                Test 2
                Tutup/Bangkrut
        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multipage_form_2_childReqBusinessConditions_subDtlBusinesCond_formDetailsBusinessConditions_dtl_business_condition973321&quot;)</value>
   </webElementProperties>
</WebElementEntity>
